import mongoose from "mongoose";

export async function connectToMongoDB() {
  try {
    const mongoUrl =
      process.env.MONGODB_URI ||
      "mongodb+srv://yash6491:YASHVANT@cluster0.f3pmu6p.mongodb.net/test?retryWrites=true&w=majority";
    await mongoose.connect(mongoUrl);
    console.log("Connected to MongoDB Atlas successfully");
  } catch (error) {
    console.error("MongoDB connection error:", error);
    throw error;
  }
}

// User Schema
const userSchema = new mongoose.Schema(
  {
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    role: {
      type: String,
      required: true,
      enum: ["sales_rep", "decision_maker", "super_admin"],
    },
    firstName: { type: String, required: true },
    lastName: { type: String, required: true },
    linkedinUrl: { type: String },
    linkedinVerified: { type: Boolean, default: false },
    jobTitle: { type: String },
    company: { type: String },
    industry: { type: String },
    companySize: { type: String },
    yearsInRole: { type: String },
    packageType: { type: String, default: "free" },
    isActive: { type: Boolean, default: true },
    standing: { type: String, default: "good" },
    // Google Calendar integration
    googleCalendarTokens: {
      access_token: { type: String },
      refresh_token: { type: String },
      scope: { type: String },
      token_type: { type: String },
      expiry_date: { type: Number }
    },
    googleCalendarId: { type: String },
    calendarIntegrationEnabled: { type: Boolean, default: false },
  },
  {
    timestamps: true,
  },
);

// Invitation Schema
const invitationSchema = new mongoose.Schema(
  {
    salesRepId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    decisionMakerEmail: { type: String, required: true },
    decisionMakerName: { type: String, required: true },
    status: {
      type: String,
      default: "pending",
      enum: ["pending", "accepted", "declined"],
    },
  },
  {
    timestamps: true,
  },
);

// Call Schema
const callSchema = new mongoose.Schema(
  {
    salesRepId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    decisionMakerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    scheduledAt: { type: Date, required: true },
    endTime: { type: Date },
    status: {
      type: String,
      default: "scheduled",
      enum: ["scheduled", "completed", "cancelled"],
    },
    rating: { type: Number, min: 1, max: 5 },
    feedback: { type: String },
    company: { type: String },
    pitch: { type: String },
    // Google Calendar integration
    googleEventId: { type: String },
    salesRepCalendarId: { type: String },
    decisionMakerCalendarId: { type: String },
    meetingLink: { type: String },
    timeZone: { type: String, default: "UTC" },
  },
  {
    timestamps: true,
  },
);

// Subscription Plan Schema
const subscriptionPlanSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    description: { type: String },
    price: { type: String, required: true },
    billingInterval: {
      type: String,
      required: true,
      enum: ["monthly", "yearly"],
      default: "monthly"
    },
    features: [{ type: String }],
    maxCallCredits: { type: Number, required: true },
    maxInvitations: { type: Number, required: true },
    prioritySupport: { type: Boolean, default: false },
    bestSeller: { type: Boolean, default: false },
    isActive: { type: Boolean, default: true },
  },
  {
    timestamps: true,
  },
);

// Flag System Schemas
const flagHistorySchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, required: true },
    userType: { type: String, enum: ['sales_rep', 'decision_maker'], required: true },
    previousFlag: { type: String, enum: ['green', 'amber', 'red'] },
    newFlag: { type: String, enum: ['green', 'amber', 'red'], required: true },
    reason: { type: String, required: true },
    severity: { type: String, enum: ['low', 'medium', 'high'], required: true },
    autoGenerated: { type: Boolean, default: true },
    resolvedAt: Date,
    createdBy: mongoose.Schema.Types.ObjectId,
    metadata: { type: mongoose.Schema.Types.Mixed }
  },
  { timestamps: true }
);

const flagRuleSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    description: { type: String, required: true },
    userType: { type: String, enum: ['sales_rep', 'decision_maker'], required: true },
    metric: { type: String, required: true },
    thresholds: {
      amber: { type: Number, required: true },
      red: { type: Number, required: true }
    },
    timeWindow: { type: Number, default: 30 },
    isActive: { type: Boolean, default: true },
    severity: { type: String, enum: ['low', 'medium', 'high'], default: 'medium' }
  },
  { timestamps: true }
);

const userFlagSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, required: true, unique: true },
    userType: { type: String, enum: ['sales_rep', 'decision_maker'], required: true },
    currentFlag: { type: String, enum: ['green', 'amber', 'red'], default: 'green' },
    flagReason: { type: String },
    flagSeverity: { type: String, enum: ['low', 'medium', 'high'], default: 'low' },
    lastCalculated: { type: Date, default: Date.now },
    violations: [{
      type: { type: String, required: true },
      count: { type: Number, default: 0 },
      lastOccurrence: { type: Date }
    }],
    metrics: {
      missedFollowups: { type: Number, default: 0 },
      invalidLeads: { type: Number, default: 0 },
      responseTime: { type: Number, default: 0 },
      complianceScore: { type: Number, default: 100 },
      callsScheduled: { type: Number, default: 0 },
      callsCompleted: { type: Number, default: 0 },
      invitationsSent: { type: Number, default: 0 },
      invitationsAccepted: { type: Number, default: 0 }
    }
  },
  { timestamps: true }
);

export const User = mongoose.model("User", userSchema);
export const Invitation = mongoose.model("Invitation", invitationSchema);
export const Call = mongoose.model("Call", callSchema);
export const SubscriptionPlan = mongoose.model("SubscriptionPlan", subscriptionPlanSchema);
export const FlagHistory = mongoose.model("FlagHistory", flagHistorySchema);
export const FlagRule = mongoose.model("FlagRule", flagRuleSchema);
export const UserFlag = mongoose.model("UserFlag", userFlagSchema);

export type UserDocument = mongoose.Document & {
  _id: mongoose.Types.ObjectId;
  email: string;
  password: string;
  role: "sales_rep" | "decision_maker";
  firstName: string;
  lastName: string;
  linkedinUrl?: string;
  linkedinVerified: boolean;
  jobTitle?: string;
  company?: string;
  industry?: string;
  companySize?: string;
  yearsInRole?: string;
  packageType: string;
  isActive: boolean;
  standing: string;
  createdAt: Date;
  updatedAt: Date;
};

export type InvitationDocument = mongoose.Document & {
  _id: mongoose.Types.ObjectId;
  salesRepId: mongoose.Types.ObjectId;
  decisionMakerEmail: string;
  decisionMakerName: string;
  status: "pending" | "accepted" | "declined";
  createdAt: Date;
  updatedAt: Date;
};

export type CallDocument = mongoose.Document & {
  _id: mongoose.Types.ObjectId;
  salesRepId: mongoose.Types.ObjectId;
  decisionMakerId: mongoose.Types.ObjectId;
  scheduledAt: Date;
  status: "scheduled" | "completed" | "cancelled";
  rating?: number;
  feedback?: string;
  company?: string;
  pitch?: string;
  createdAt: Date;
  updatedAt: Date;
};

export type SubscriptionPlanDocument = mongoose.Document & {
  _id: mongoose.Types.ObjectId;
  name: string;
  description?: string;
  price: string;
  billingInterval: "monthly" | "yearly";
  features: string[];
  maxCallCredits: number;
  maxInvitations: number;
  prioritySupport: boolean;
  bestSeller: boolean;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
};

export type FlagHistoryDocument = mongoose.Document & {
  _id: mongoose.Types.ObjectId;
  userId: mongoose.Types.ObjectId;
  userType: 'sales_rep' | 'decision_maker';
  previousFlag?: 'green' | 'amber' | 'red';
  newFlag: 'green' | 'amber' | 'red';
  reason: string;
  severity: 'low' | 'medium' | 'high';
  autoGenerated: boolean;
  resolvedAt?: Date;
  createdBy?: mongoose.Types.ObjectId;
  metadata?: any;
  createdAt: Date;
  updatedAt: Date;
};

export type FlagRuleDocument = mongoose.Document & {
  _id: mongoose.Types.ObjectId;
  name: string;
  description: string;
  userType: 'sales_rep' | 'decision_maker';
  metric: string;
  thresholds: {
    amber: number;
    red: number;
  };
  timeWindow: number;
  isActive: boolean;
  severity: 'low' | 'medium' | 'high';
  createdAt: Date;
  updatedAt: Date;
};

export type UserFlagDocument = mongoose.Document & {
  _id: mongoose.Types.ObjectId;
  userId: mongoose.Types.ObjectId;
  userType: 'sales_rep' | 'decision_maker';
  currentFlag: 'green' | 'amber' | 'red';
  flagReason?: string;
  flagSeverity: 'low' | 'medium' | 'high';
  lastCalculated: Date;
  violations: Array<{
    type: string;
    count: number;
    lastOccurrence?: Date;
  }>;
  metrics: {
    missedFollowups: number;
    invalidLeads: number;
    responseTime: number;
    complianceScore: number;
    callsScheduled: number;
    callsCompleted: number;
    invitationsSent: number;
    invitationsAccepted: number;
  };
  createdAt: Date;
  updatedAt: Date;
};
